name: Mirror to Org Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Remove workflow file
        run: |
          # Remove the mirror workflow so it doesn't appear in org repo
          rm -rf .github/workflows/mirror-to-org.yml
          git add .github/workflows/mirror-to-org.yml
          git commit -m "Remove mirror workflow" || echo "No changes to commit"

      - name: Push to organization repo
        env:
          GH_TOKEN: ${{ secrets.ORG_REPO_PAT }}
        run: |
          git remote add org https://${{ secrets.ORG_REPO_PAT }}@github.com/BOLT-UBC/BOLT-website-2025.git

          # Push all branches
          git push org --all --force

          # Push all tags
          git push org --tags --force

          echo "✅ Successfully mirrored to org repo (workflow excluded)"


