name: Mirror to Org

# Automatically mirrors code to BOLT-UBC organization repo
on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to org repo
        run: |
          git remote add org https://x-access-token:${{secrets.ORG_REPO_PAT}}@github.com/BOLT-UBC/BOLT-website-2025.git
          git push org main --force
